### ISSUE TITLE
Feature request: make Slack integration optional

### ISSUE THREAD

**Issue by davidneedham** [pantheon-systems/example-terminus-auto-update-script#35]
In a training today the agency didn't want to integrate with Slack so they simply skipped adding those environment variables. When the build ran it failed because it wasn't able to talk to Slack. Ultimately it wasn't a big deal because they _do_ use Slack and were able to go back and add that information.

A dev should be able to choose if they want to integrate the auto update script with Slack. It should not be a hard requirement because CircleCI will notify the dev about errors via email regardless.

**Comment by justinwhall** [comment]
+1 here. I'd be interested in giving this a sping but we do not use Slack at work.

**Comment by ataylorme** [comment]
> It should not be a hard requirement because CircleCI will notify the dev about errors via email regardless.

That is not entirely true. The builds for the automated tests pass even if the tests fail. I suppose I could fail the build. Currently, if someone wants to use a communication method other than Slack they can modify the script after forking it. I don't want to maintain/support a multitude of options.

I'll have to do some more thinking on whether to make Slack optional. I could just check for the environment variables to be set and, if they are not set, simply don't ping the Slack API.

**Comment by ataylorme** [comment]
I'm closing this issue so we can archive this repository. It is a reference implementation, not a product to be used. [See this comment on the README](https://github.com/pantheon-systems/example-terminus-auto-update-script#repository-archived-2019-06-13)
