### ISSUE TITLE
Periodic timeouts on Visual Regression Tests: Too long with no output (exceeded 30m0s)

### ISSUE THREAD

**Issue by mcdwayne** [pantheon-systems/example-terminus-auto-update-script#43]
Installed per directions and about 1 our of 3 times this runs I hit this issue:

Failing command: run visual regression tests 
Exit code: 
Output:
lled, version 1.4.1
9468 INFO >  BackstopTools have been installed.
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1920,1080"],"port":9469,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=320,480"],"port":9470,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
9469 Chrome v66 detected.
9469 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9470 Chrome v66 detected.
9469 INFO >  BackstopTools have been installed.
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=568,1024"],"port":9471,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1024,768"],"port":9472,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
9470 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9470 INFO >  BackstopTools have been installed.
9471 Chrome v66 detected.
9471 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9472 Chrome v66 detected.
9472 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1920,1080"],"port":9473,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
9471 INFO >  BackstopTools have been installed.
9472 INFO >  BackstopTools have been installed.
9473 Chrome v66 detected.
9473 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9473 INFO >  BackstopTools have been installed.
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=320,480"],"port":9474,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=568,1024"],"port":9475,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
9474 Chrome v66 detected.
9475 Chrome v66 detected.
9474 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9475 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9474 INFO >  BackstopTools have been installed.
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1024,768"],"port":9476,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
9475 INFO >  BackstopTools have been installed.
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1920,1080"],"port":9477,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
9476 Chrome v66 detected.
9476 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9477 Chrome v66 detected.
9477 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9476 INFO >  BackstopTools have been installed.
9477 INFO >  BackstopTools have been installed.
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=320,480"],"port":9478,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
9478 Chrome v66 detected.
9478 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=568,1024"],"port":9479,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1024,768"],"port":9480,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
9479 Chrome v66 detected.
9479 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9480 Chrome v66 detected.
9480 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1920,1080"],"port":9481,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=320,480"],"port":9482,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
9481 Chrome v66 detected.
9481 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9482 Chrome v66 detected.
9482 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9478 INFO >  BackstopTools have been installed.
9482 INFO >  BackstopTools have been installed.
9479 INFO >  BackstopTools have been installed.
9480 INFO >  BackstopTools have been installed.
9481 INFO >  BackstopTools have been installed.
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=568,1024"],"port":9483,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
9483 Chrome v66 detected.
9483 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9483 INFO >  BackstopTools have been installed.
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1024,768"],"port":9484,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
9484 Chrome v66 detected.
9484 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9484 INFO >  BackstopTools have been installed.
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1920,1080"],"port":9485,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
9485 Chrome v66 detected.
9485 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9485 INFO >  BackstopTools have been installed.
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=320,480"],"port":9486,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
9486 Chrome v66 detected.
9486 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9486 INFO >  BackstopTools have been installed.
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=568,1024"],"port":9487,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
9487 Chrome v66 detected.
9487 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9487 INFO >  BackstopTools have been installed.
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1024,768"],"port":9488,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
9488 Chrome v66 detected.
9488 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9488 INFO >  BackstopTools have been installed.
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1920,1080"],"port":9489,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
9489 Chrome v66 detected.
9489 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9489 INFO >  BackstopTools have been installed.
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=320,480"],"port":9490,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
9490 Chrome v66 detected.
9490 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9490 INFO >  BackstopTools have been installed.
9490 LOG >  [Amplitude] WARNING: Property key "appMode" with invalid value type null, ignoring
9490 LOG >  [Amplitude] WARNING: Property key "channelId" with invalid value type null, ignoring
9490 LOG >  [Amplitude] WARNING: Property key "appMode" with invalid value type null, ignoring
9490 LOG >  [Amplitude] WARNING: Property key "channelId" with invalid value type null, ignoring
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=568,1024"],"port":9491,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
9491 Chrome v66 detected.
9491 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9491 INFO >  BackstopTools have been installed.
9491 LOG >  [Amplitude] WARNING: Property key "appMode" with invalid value type null, ignoring
9491 LOG >  [Amplitude] WARNING: Property key "channelId" with invalid value type null, ignoring
9491 LOG >  [Amplitude] WARNING: Property key "appMode" with invalid value type null, ignoring
9491 LOG >  [Amplitude] WARNING: Property key "channelId" with invalid value type null, ignoring
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1024,768"],"port":9492,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
9492 Chrome v66 detected.
9492 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9492 INFO >  BackstopTools have been installed.
9492 LOG >  [Amplitude] WARNING: Property key "appMode" with invalid value type null, ignoring
9492 LOG >  [Amplitude] WARNING: Property key "channelId" with invalid value type null, ignoring
9492 LOG >  [Amplitude] WARNING: Property key "appMode" with invalid value type null, ignoring
9492 LOG >  [Amplitude] WARNING: Property key "channelId" with invalid value type null, ignoring
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1920,1080"],"port":9493,"waitTimeout":30000,"visible":false}
CREATING NEW REFERENCE FILES
9493 Chrome v66 detected.
9493 LOG >  JQMIGRATE: Migrate is installed, version 1.4.1
9493 INFO >  BackstopTools have been installed.
Too long with no output (exceeded 30m0s)
The rest of your commands were successful:
Spin up Environment
Checkout code
declare environment variables
Uploading artifacts

**Comment by ataylorme** [comment]
@mcdwayne how many URLs are you checking? If you can add me to your repo so I can look at it and CircleCI directly that would help.

**Comment by mcdwayne** [comment]
Thanks,
I am checking 3 URLs only, just looking at the front pages of three sites I am maintaining.  
Just added you to my repo mcdwayne/mcdwaynedotcom-auto-update

Thanks,

Dwayne

**Comment by ataylorme** [comment]
Can you link the CircleCI build with this result? The one I looked at [39](https://circleci.com/gh/mcdwayne/mcdwaynedotcom-auto-update/39) failed because it looks like Slack is not hooked up.

```
Tests passed! WordPress updates deployed to live for advisingmindfully...

Sending a message to the  Slack channel
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
Exited with code 2
```

**Comment by mcdwayne** [comment]
This one. 
https://circleci.com/gh/mcdwayne/mcdwaynedotcom-auto-update/36

It is weird the other one failed due to slack, I thought I had removed all referenced to slack calls (didn't want to hook this part up).  Odd it passes on the others

**Comment by ataylorme** [comment]
@mcdwayne BackstopJS times out since it is trying to process too many URLs. By default the script crawls the sites. See [the README](https://github.com/pantheon-systems/example-terminus-auto-update-script#configuring-backstop-js) for details. Basically you need a `SITE_NAME.backstop.json` for each site if you want to just have it run for the homepage.

**Comment by mcdwayne** [comment]
Issue though is there are only 59 posts on this site and 9 pages.  Close to but not close enough to ~100 for me to catch this when troubleshooting.  Would suggest that you modify that Readme to ~50 instead 
backstop-crawl on sites with many (~50+)

**Comment by ataylorme** [comment]
You aren't counting taxonomy pages (date archives, category archives), images (each image gets its own page), etc.

**Comment by mcdwayne** [comment]
Wow, well, if that is the case the lower limit should be even smaller then shouldn't it.  If I have a single page with 100 images on it, by that logic this will just fail by default.  
In fact other than static sites, would this be useful as is for any publication sites? Those will all continually grow as content is generated (which is the central use case for WP)  
Not criticizing here, love this idea, but known limitations, as is, does not warn against this enough.

**Comment by mcdwayne** [comment]
As you inferred from my previous comments, I thought that was how it worked by default.  I had implemented the old one without the site crawl and updates to this one without reading the Readme thoroughly, so while I am happy it passed when it did, caught me off guard.  User error really. 

If default was ONLY homepage, with an explanation that you can add in the Crawl for smaller sites without a lot of posts and will need to form strategy around larger and growing sites if you want every page checked, I think it would be better. 

Given the user issue on this one, maybe no action is needed.  

On the other hand, this is meant as an example repo I think, so simplifying (without the crawler) it is easier to wrap brain around it since less moving parts...
