### ISSUE TITLE
drush pm-updatestatus

### ISSUE THREAD

**Issue by davidneedham** [pantheon-systems/example-terminus-auto-update-script#46]
When the script runs on a Drupal site I get the error `[error]   The drush command 'pm-updatestatus' could not be found. Run `drush [error] cache-clear drush` to clear the commandfile cache if you have installed new extensions.`

See https://drushcommands.com/drush-9x/pm/pm:updatestatus/ :

> The pm-updatestatus command was deprecated. Please see `composer show` and `composer outdated`. For security release notification, see `drush pm:security`.

**Comment by ataylorme** [comment]
I'm closing this issue so we can archive this repository. It is a reference implementation, not a product to be used. [See this comment on the README](https://github.com/pantheon-systems/example-terminus-auto-update-script#repository-archived-2019-06-13)
