### ISSUE TITLE
Add support for Bitbucket

### ISSUE THREAD

**Issue by davidneedham** [pantheon-systems/example-terminus-auto-update-script#47]
As it is, the code example expects GitHub. I swapped out places where `https://circleci.com/api/v1.1/project/github/...` with `https://circleci.com/api/v1.1/project/bitbucket/`, crossed my fingers, and everything seems to have worked.

Is there a Circle environment variable or something we can use to say where it's coming from? Or is there a way to et Circle detect it automatically?

**Comment by kevcooper** [comment]
[CIRCLE_REPOSITORY_URL](https://circleci.com/docs/2.0/env-vars/) seems like the best candidate to me

**Comment by ataylorme** [comment]
Sorry for the delayed reply. [Here](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables) is a list of environment variables set by CircleCI.

**Comment by ataylorme** [comment]
can you elaborate more on the use case for storing the project in BitBucket instead of GitHub?

**Comment by davidneedham** [comment]
> can you elaborate more on the use case for storing the project in BitBucket instead of GitHub?

Some organizations prefer Bitbucket. They may have institutional knowledge, users, and workflows in place there already. They may prefer a (free) private repo for a project like this where client site names and URLs would otherwise be visible.

I agree with @kevcooper.

**Comment by ataylorme** [comment]
I agree some folks will prefer BitBucket. With that said this is an example meant to show what is possible with Pantheon and automated testing. If someone wants to use a different configuration/environment to run the scripts then they are welcome to do so but will need to make the necessary updates to the scripts on their own.

There are too many variations to maintain an example of each one. The work to adapt this script to BitBucket, for example, compared to starting from scratch is minimal. This repository is meant to inspire and show what is possible, not be a direct copy/paste solution.

@davidneedham if you want to submit a PR outlining what areas need to be updated to make the scripts work on other providers I am open to that but do not want to add additional logic or variation to the example scripts.

**Comment by ataylorme** [comment]
I'm closing this issue so we can archive this repository. It is a reference implementation, not a product to be used. [See this comment on the README](https://github.com/pantheon-systems/example-terminus-auto-update-script#repository-archived-2019-06-13)
