### ISSUE TITLE
Failed with Permission Denied

### ISSUE THREAD

**Issue by halyburton** [pantheon-systems/example-terminus-auto-update-script#48]
I am working on setting this up to update  a growing lists of Wordpress sites, but am having issues. I have followed the guide in the readme, but when it fails on build or update. i get a permission denied.

`#!/bin/bash -eo pipefail
./.circleci/set-up-globals.sh
/bin/bash: ./.circleci/set-up-globals.sh: Permission denied
Exited with code 1`

My google search says that the scripts are not executable, but i am not sure what that means in CircleCi. I tried the alt option to add 'sh' before calling the bash script. That gets further, but then fails with 

`
#!/bin/bash -eo pipefail
sh ./.circleci/set-up-globals.sh
 [ -z auto-update ]
 echo export GREEN_HEX="008000"
 echo export RED_HEX="FF0000"
 openssl rand -hex 8
 RANDOM_PASS=2d868331a59814fa
 echo export CMS_ADMIN_USERNAME='pantheon'
 echo export CMS_ADMIN_PASSWORD='2d868331a59814fa'
 echo export MULTIDEV_URL='https://auto-update-.pantheonsite.io/'
 [ -z  ]
 echo export LIVE_URL='https://live-.pantheonsite.io/'
 echo export PATH=$PATH:$HOME/bin:$HOME/terminus/bin
 source /tmp/.bash_env-5c0960269536c30008d67b59-0-build
./.circleci/set-up-globals.sh: 42: ./.circleci/set-up-globals.sh: source: not found
Exited with code 127
`

Is there something that is not documented that i am missing? Seems like i haven't even gotten past the first step.

Thanks

**Comment by halyburton** [comment]
I think i figured it, the calls to bash now need to start with "bash " in the config.yml, so it looks like 

`command: bash ./.circleci/sites-to-update.sh`

**Comment by ataylorme** [comment]
@halyburton sorry I missed this - I've been out traveling for a conference. Glad you got it working!
